config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # ----------
  # api
  # ----------
  mount_devise_token_auth_for 'User', at: 'api/v1/auth', controllers: {
    registrations: 'api/v1/auth/registrations'
  }
  namespace :api do
    namespace :v1 do
      resources :addresses
      resources :contacts,     only: %i[create]
      resources :coordinates,  only: %i[index show]
      resources :informations, only: %i[index show]
      resources :orders,       only: %i[index show]
      resources :pages,        only: %i[index show]
      resources :products,     only: %i[index show]
      resources :rankings,     only: %i[index show]
      resources :stores,       only: %i[index show]
      resources :store_blogs,  only: %i[index show]
      resources :variations,   only: %i[index show]
    end
  end

  # ----------
  # admin
  # ----------
  devise_for :admins, path: 'admin/auth', skip: %i[registrations], controllers: {
    sessions: 'admin/auth/sessions',
    unlocks:  'admin/auth/unlocks'
  }
  # only use update(disable sign up)
  as :admin do
    get 'admin/auth/edit' => 'admin/auth/registrations#edit', as: 'edit_admin_registration'
    put 'admin/auth' => 'admin/auth/registrations#update', as: 'admin_registration'
  end
  namespace :admin do
    root 'dashboards#show'
    resources :admins
    resources :brands
    resources :categories
    resources :colors
    resources :companies
    resources :contacts
    resources :coordinates
    resources :divisions
    resources :informations
    resources :pages
    resources :positions
    resources :products
    resources :orders
    resources :rankings
    resources :sizes
    resources :staffs
    resources :stores
    resources :store_blogs
    resources :tags
    resources :users
    resources :variations
  end
end

app/models/information.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: informations
#
#  id               :bigint(8)        not null, primary key
#  release_datetime :datetime
#  subject          :string(255)
#  content          :text(65535)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Information < ApplicationRecord
end

app/controllers/admin/informations_controller.rb
# frozen_string_literal: true

class Admin::InformationsController < Admin::ApplicationController
  before_action :set_information, only: %i[show edit update destroy]

  # GET /informations
  def index
    @q = Information.search(params[:q])
    authorize @informations = @q.result.page(params[:page])
  end

  # GET /informations/1
  def show; end

  # GET /informations/new
  def new
    authorize @information = Information.new
  end

  # GET /informations/1/edit
  def edit; end

  # POST /informations
  def create
    authorize @information = Information.new(information_params)

    if @information.save
      redirect_to [:admin, @information], notice: t('notice.create.success', name: Information.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /informations/1
  def update
    if @information.update(information_params)
      redirect_to [:admin, @information], notice: t('notice.update.success', name: Information.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /informations/1
  def destroy
    @information.destroy
    redirect_to admin_informations_url, notice: t('notice.destroy.success', name: Information.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_information
    authorize @information = Information.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def information_params
    params.require(:information).permit(:release_datetime, :subject, :content)
  end
end

app/controllers/api/v1/informations_controller.rb
# frozen_string_literal: true

class Api::V1::InformationsController < Api::V1::ApplicationController
  before_action :set_information, only: %i[show]

  # GET /informations
  def index
    @informations = Information.search(params[:q]).result
                               .order(release_datetime: :desc).page(params[:page]).per(params[:per_page])

    paginate json: @informations
  end

  # GET /informations/1
  def show
    render json: @information
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_information
    @information = Information.find(params[:id])
  end
end

app/views/admin/informations/_form.html.erb
<%= form_with(model: [:admin, information], local: true) do |form| %>
  <%= render 'shared/form_errors', errors: information.errors %>

  <div class="form-group">
    <%= form.label :release_datetime %>
    <%= form.datetime_select :release_datetime, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :subject %>
    <%= form.text_area :subject, class: 'form-control', rows: 4 %>
    <small class="form-text text-muted"><%= t('text.can_use_html_tag') %></small>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control', rows: 20 %>
    <small class="form-text text-muted"><%= t('text.can_use_html_tag') %></small>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/informations/edit.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.edit') %> <%= Information.model_name.human %>
        </h1>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= render 'form', information: @information %>
          </div>
          <div class="card-footer clearfix">
            <%= link_to(t('text.show'), [:admin, @information], class: 'card-link') if policy(@information).show? %>
            <%= link_to(t('text.back'), admin_informations_path, class: 'card-link') if policy(Information).index? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/informations/index.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= Information.model_name.human %>
        </h1>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-12">
        <%= render 'shared/alert', alert: notice %>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <i class="fa fa-pencil"></i> <%= page_entries_info @informations %>
            <div class="card-tools d-flex">
              <%= link_to(t('text.new'), new_admin_information_path, class: 'mr-3 mt-1') if policy(Information).create? %>
              <%= paginate @informations %>
            </div>
          </div><!-- /.card-header -->
          <div class="card-body p-0 table-responsive">
            <table class="table table-hover table-striped">
              <thead>
                <tr>
                  <th><%= sort_link(@q, :release_datetime) %></th>
                  <th><%= Information.human_attribute_name(:subject) %></th>
                  <th><%= Information.human_attribute_name(:content) %></th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @informations.each do |information| %>
                  <tr>
                    <td><%= information.release_datetime %></td>
                    <td><%= information.subject %></td>
                    <td><%= information.content %></td>
                    <td><%= link_to(t('text.show'), [:admin, information]) if policy(information).show? %></td>
                    <td><%= link_to(t('text.edit'), edit_admin_information_path(information)) if policy(information).update? %></td>
                    <td><%= link_to(t('text.destroy'), [:admin, information], method: :delete, data: { confirm: t('text.are_you_sure') }) if policy(information).destroy? %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div><!-- /.card-body -->
          <div class="card-footer clearfix">
            <%= paginate @informations %>
          </div>
        </div><!-- /.card -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</section>

app/views/admin/informations/new.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.new') %> <%= Information.model_name.human %>
        </h1>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= render 'form', information: @information %>
          </div>
          <div class="card-footer clearfix">
            <%= link_to t('text.back'), admin_informations_path, class: 'card-link' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/informations/show.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.show') %> <%= Information.model_name.human %>
        </h1>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-12">
        <%= render 'shared/alert', alert: notice %>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <dl>
              <dt><%= Information.human_attribute_name(:release_datetime) %></dt>
              <dd><%= @information.release_datetime %></dd>
            </dl>
            <dl>
              <dt><%= Information.human_attribute_name(:subject) %></dt>
              <dd><%= sanitize @information.subject %></dd>
            </dl>
            <dl>
              <dt><%= Information.human_attribute_name(:content) %></dt>
              <dd><%= sanitize @information.content %></dd>
            </dl>
          </div>
          <div class="card-footer clearfix">
            <%= link_to(t('text.edit'), edit_admin_information_path(@information), class: 'card-link') if policy(@information).update? %>
            <%= link_to(t('text.back'), admin_informations_path, class: 'card-link') if policy(Information).index? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>