config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # ----------
  # api
  # ----------
  mount_devise_token_auth_for 'User', at: 'api/v1/auth', controllers: {
    registrations: 'api/v1/auth/registrations'
  }
  namespace :api do
    namespace :v1 do
      resources :addresses
      resources :contacts,     only: %i[create]
      resources :coordinates,  only: %i[index show]
      resources :informations, only: %i[index show]
      resources :orders,       only: %i[index show]
      resources :pages,        only: %i[index show]
      resources :products,     only: %i[index show]
      resources :rankings,     only: %i[index show]
      resources :stores,       only: %i[index show]
      resources :store_blogs,  only: %i[index show]
      resources :variations,   only: %i[index show]
    end
  end

  # ----------
  # admin
  # ----------
  devise_for :admins, path: 'admin/auth', skip: %i[registrations], controllers: {
    sessions: 'admin/auth/sessions',
    unlocks:  'admin/auth/unlocks'
  }
  # only use update(disable sign up)
  as :admin do
    get 'admin/auth/edit' => 'admin/auth/registrations#edit', as: 'edit_admin_registration'
    put 'admin/auth' => 'admin/auth/registrations#update', as: 'admin_registration'
  end
  namespace :admin do
    root 'dashboards#show'
    resources :admins
    resources :brands
    resources :categories
    resources :colors
    resources :companies
    resources :contacts
    resources :coordinates
    resources :divisions
    resources :informations
    resources :pages
    resources :positions
    resources :products
    resources :orders
    resources :rankings
    resources :sizes
    resources :staffs
    resources :stores
    resources :store_blogs
    resources :tags
    resources :users
    resources :variations
  end
end

app/models/order.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: orders
#
#  id             :bigint(8)        not null, primary key
#  category       :integer
#  status         :integer
#  payment_status :integer
#  user_id        :bigint(8)
#  first_name     :string(255)
#  last_name      :string(255)
#  first_kana     :string(255)
#  last_kana      :string(255)
#  postal_code    :string(255)
#  prefecture_id  :bigint(8)
#  address_1      :string(255)
#  address_2      :string(255)
#  address_3      :string(255)
#  tel_no         :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :prefecture
  has_many :orders_variations, dependent: :destroy
  has_many :variations, through: :orders_variations

  enum category: %i[normal pre_order back_order]
  # 発送ステータス: 引当待ち、発送待ち、発送完了、キャンセル
  enum status: %i[waiting_allocation waiting_shipping shipped cancel]
  # 支払ステータス: 支払待ち、支払完了、返金待ち、返金完了
  enum payment_status: %i[waiting_payment paid waiting_refundment refunded]
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

class Admin::OrdersController < Admin::ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders
  def index
    @q = Order.includes(:user, :prefecture).search(params[:q])
    authorize @orders = @q.result.page(params[:page])
  end

  # GET /orders/1
  def show; end

  # GET /orders/new
  def new
    authorize @order = Order.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders
  def create
    authorize @order = Order.new(order_params)

    if @order.save
      redirect_to [:admin, @order], notice: t('notice.create.success', name: Order.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to [:admin, @order], notice: t('notice.update.success', name: Order.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to admin_orders_url, notice: t('notice.destroy.success', name: Order.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    authorize @order = Order.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def order_params
    params.require(:order).permit(:category, :status, :payment_status, :user_id,
                                  :last_name, :first_name, :last_kana, :first_kana, :postal_code,
                                  :prefecture_id, :address_1, :address_2, :address_3, :tel_no)
  end
end

app/controllers/api/v1/orders_controller.rb
# frozen_string_literal: true

class Api::V1::OrdersController < Api::V1::ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show]

  # GET /orders
  def index
    @orders = Order.where(user: current_user)
                   .search(params[:q]).result
                   .page(params[:page]).per(params[:per_page])

    paginate json: @orders
  end

  # GET /orders/1
  def show
    render json: @order
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.where(user: current_user).find(params[:id])
  end
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, order], local: true) do |form| %>
  <%= render 'shared/form_errors', errors: order.errors %>

  <div class="form-group">
    <%= form.label :category %>
    <%= form.select :category, Order.categories.keys, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, Order.statuses.keys, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :payment_status %>
    <%= form.select :payment_status, Order.payment_statuses.keys, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :nickname, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_kana %>
    <%= form.text_field :last_kana, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :first_kana %>
    <%= form.text_field :first_kana, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :prefecture_id %>
    <%= form.collection_select :prefecture_id, Prefecture.all, :id, :name, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address_1 %>
    <%= form.text_field :address_1, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address_2 %>
    <%= form.text_field :address_2, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address_3 %>
    <%= form.text_field :address_3, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :tel_no %>
    <%= form.text_field :tel_no, class: 'form-control' %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/orders/edit.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.edit') %> <%= Order.model_name.human %>
        </h1>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= render 'form', order: @order %>
          </div>
          <div class="card-footer clearfix">
            <%= link_to(t('text.show'), [:admin, @order], class: 'card-link') if policy(@order).show? %>
            <%= link_to(t('text.back'), admin_orders_path, class: 'card-link') if policy(Order).index? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/orders/index.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= Order.model_name.human %>
        </h1>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-12">
        <%= render 'shared/alert', alert: notice %>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <i class="fa fa-pencil"></i> <%= page_entries_info @orders %>
            <div class="card-tools d-flex">
              <%= link_to(t('text.new'), new_admin_order_path, class: 'mr-3 mt-1') if policy(Order).create? %>
              <%= paginate @orders %>
            </div>
          </div><!-- /.card-header -->
          <div class="card-body p-0 table-responsive">
            <table class="table table-hover table-striped">
              <thead>
                <tr>
                  <th><%= Order.human_attribute_name(:category) %></th>
                  <th><%= Order.human_attribute_name(:status) %></th>
                  <th><%= Order.human_attribute_name(:payment_status) %></th>
                  <th><%= Order.human_attribute_name(:user_id) %></th>
                  <th><%= Order.human_attribute_name(:last_name) %></th>
                  <th><%= Order.human_attribute_name(:first_name) %></th>
                  <th><%= Order.human_attribute_name(:last_kana) %></th>
                  <th><%= Order.human_attribute_name(:first_kana) %></th>
                  <th><%= Order.human_attribute_name(:postal_code) %></th>
                  <th><%= Order.human_attribute_name(:prefecture_id) %></th>
                  <th><%= Order.human_attribute_name(:address_1) %></th>
                  <th><%= Order.human_attribute_name(:address_2) %></th>
                  <th><%= Order.human_attribute_name(:address_3) %></th>
                  <th><%= Order.human_attribute_name(:tel_no) %></th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @orders.each do |order| %>
                  <tr>
                    <td><%= order.category %></td>
                    <td><%= order.status %></td>
                    <td><%= order.payment_status %></td>
                    <td><%= order.user&.nickname %></td>
                    <td><%= order.last_name %></td>
                    <td><%= order.first_name %></td>
                    <td><%= order.last_kana %></td>
                    <td><%= order.first_kana %></td>
                    <td><%= order.postal_code %></td>
                    <td><%= order.prefecture&.name %></td>
                    <td><%= order.address_1 %></td>
                    <td><%= order.address_2 %></td>
                    <td><%= order.address_3 %></td>
                    <td><%= order.tel_no %></td>
                    <td><%= link_to(t('text.show'), [:admin, order]) if policy(order).show? %></td>
                    <td><%= link_to(t('text.edit'), edit_admin_order_path(order)) if policy(order).update? %></td>
                    <td><%= link_to(t('text.destroy'), [:admin, order], method: :delete, data: { confirm: t('text.are_you_sure') }) if policy(order).destroy? %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div><!-- /.card-body -->
          <div class="card-footer clearfix">
            <%= paginate @orders %>
          </div>
        </div><!-- /.card -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</section>

app/views/admin/orders/new.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.new') %> <%= Order.model_name.human %>
        </h1>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= render 'form', order: @order %>
          </div>
          <div class="card-footer clearfix">
            <%= link_to t('text.back'), admin_orders_path, class: 'card-link' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/orders/show.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.show') %> <%= Order.model_name.human %>
        </h1>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-12">
        <%= render 'shared/alert', alert: notice %>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <dl>
              <dt><%= Order.human_attribute_name(:category) %></dt>
              <dd><%= @order.category %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:status) %></dt>
              <dd><%= @order.status %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:payment_status) %></dt>
              <dd><%= @order.payment_status %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:user_id) %></dt>
              <dd><%= @order.user&.nickname %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:last_name) %></dt>
              <dd><%= @order.last_name %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:first_name) %></dt>
              <dd><%= @order.first_name %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:last_kana) %></dt>
              <dd><%= @order.last_kana %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:first_kana) %></dt>
              <dd><%= @order.first_kana %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:postal_code) %></dt>
              <dd><%= @order.postal_code %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:prefecture_id) %></dt>
              <dd><%= @order.prefecture&.name %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:address_1) %></dt>
              <dd><%= @order.address_1 %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:address_2) %></dt>
              <dd><%= @order.address_2 %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:address_3) %></dt>
              <dd><%= @order.address_3 %></dd>
            </dl>
            <dl>
              <dt><%= Order.human_attribute_name(:tel_no) %></dt>
              <dd><%= @order.tel_no %></dd>
            </dl>
          </div>
          <div class="card-footer clearfix">
            <%= link_to(t('text.edit'), edit_admin_order_path(@order), class: 'card-link') if policy(@order).update? %>
            <%= link_to(t('text.back'), admin_orders_path, class: 'card-link') if policy(Order).index? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>