config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # ----------
  # api
  # ----------
  mount_devise_token_auth_for 'User', at: 'api/v1/auth', controllers: {
    registrations: 'api/v1/auth/registrations'
  }
  namespace :api do
    namespace :v1 do
      resources :addresses
      resources :contacts,     only: %i[create]
      resources :coordinates,  only: %i[index show]
      resources :informations, only: %i[index show]
      resources :orders,       only: %i[index show]
      resources :pages,        only: %i[index show]
      resources :products,     only: %i[index show]
      resources :rankings,     only: %i[index show]
      resources :stores,       only: %i[index show]
      resources :store_blogs,  only: %i[index show]
      resources :variations,   only: %i[index show]
    end
  end

  # ----------
  # admin
  # ----------
  devise_for :admins, path: 'admin/auth', skip: %i[registrations], controllers: {
    sessions: 'admin/auth/sessions',
    unlocks:  'admin/auth/unlocks'
  }
  # only use update(disable sign up)
  as :admin do
    get 'admin/auth/edit' => 'admin/auth/registrations#edit', as: 'edit_admin_registration'
    put 'admin/auth' => 'admin/auth/registrations#update', as: 'admin_registration'
  end
  namespace :admin do
    root 'dashboards#show'
    resources :admins
    resources :brands
    resources :categories
    resources :colors
    resources :companies
    resources :contacts
    resources :coordinates
    resources :divisions
    resources :informations
    resources :pages
    resources :positions
    resources :products
    resources :orders
    resources :rankings
    resources :sizes
    resources :staffs
    resources :stores
    resources :store_blogs
    resources :tags
    resources :users
    resources :variations
  end
end

app/models/store.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: stores
#
#  id            :bigint(8)        not null, primary key
#  name          :string(255)
#  code          :string(255)
#  postal_code   :string(255)
#  prefecture_id :bigint(8)
#  address_1     :string(255)
#  address_2     :string(255)
#  address_3     :string(255)
#  tel_no        :string(255)
#  blog_url      :string(255)
#  rss_url       :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Store < ApplicationRecord
  has_many :staffs, dependent: :restrict_with_error
  belongs_to :prefecture
  has_one :store_blog, dependent: :restrict_with_error

  has_one_attached :image

  def address
    "#{prefecture&.name}#{address_1}#{address_2} #{address_3}"
  end

  def image_path
    return unless image.attached?
    URI.join(
      Rails.application.config.action_controller.asset_host,
      Rails.application.routes.url_helpers.rails_blob_path(image, only_path: true)
    )
  end
end

app/controllers/admin/stores_controller.rb
# frozen_string_literal: true

class Admin::StoresController < Admin::ApplicationController
  before_action :set_store, only: %i[show edit update destroy]

  # GET /stores
  def index
    @q = Store.includes(:prefecture).with_attached_image.search(params[:q])
    authorize @stores = @q.result.page(params[:page])
  end

  # GET /stores/1
  def show; end

  # GET /stores/new
  def new
    authorize @store = Store.new
  end

  # GET /stores/1/edit
  def edit; end

  # POST /stores
  def create
    authorize @store = Store.new(store_params)

    if @store.save
      redirect_to [:admin, @store], notice: t('notice.create.success', name: Store.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /stores/1
  def update
    if @store.update(store_params)
      redirect_to [:admin, @store], notice: t('notice.update.success', name: Store.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /stores/1
  def destroy
    @store.destroy
    redirect_to admin_stores_url, notice: t('notice.destroy.success', name: Store.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    authorize @store = Store.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def store_params
    params.require(:store).permit(:name, :code, :postal_code, :prefecture_id,
                                  :address_1, :address_2, :address_3, :tel_no, :blog_url, :rss_url, :image)
  end
end

app/controllers/api/v1/stores_controller.rb
# frozen_string_literal: true

class Api::V1::StoresController < Api::V1::ApplicationController
  before_action :set_store, only: %i[show]

  # GET /stores
  def index
    @stores = Store.includes(:prefecture)
                   .with_attached_image
                   .search(params[:q]).result
                   .page(params[:page]).per(params[:per_page])

    paginate json: @stores
  end

  # GET /stores/1
  def show
    render json: @store
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end
end

app/views/admin/stores/_form.html.erb
<%= form_with(model: [:admin, store], local: true) do |form| %>
  <%= render 'shared/form_errors', errors: store.errors %>

  <div class="form-group">
    <%= form.label :image %>
    <div><%= thumbnail store.image %></div>
    <%= form.file_field :image, class: 'form-control-file' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :code %>
    <%= form.text_field :code, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :prefecture_id %>
    <%= form.collection_select :prefecture_id, Prefecture.all, :id, :name, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address_1 %>
    <%= form.text_field :address_1, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address_2 %>
    <%= form.text_field :address_2, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address_3 %>
    <%= form.text_field :address_3, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :tel_no %>
    <%= form.text_field :tel_no, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :blog_url %>
    <%= form.text_field :blog_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :rss_url %>
    <%= form.text_field :rss_url, class: 'form-control' %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/stores/edit.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.edit') %> <%= Store.model_name.human %>
        </h1>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= render 'form', store: @store %>
          </div>
          <div class="card-footer clearfix">
            <%= link_to(t('text.show'), [:admin, @store], class: 'card-link') if policy(@store).show? %>
            <%= link_to(t('text.back'), admin_stores_path, class: 'card-link') if policy(Store).index? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/stores/index.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= Store.model_name.human %>
        </h1>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-12">
        <%= render 'shared/alert', alert: notice %>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <i class="fa fa-pencil"></i> <%= page_entries_info @stores %>
            <div class="card-tools d-flex">
              <%= link_to(t('text.new'), new_admin_store_path, class: 'mr-3 mt-1') if policy(Store).create? %>
              <%= paginate @stores %>
            </div>
          </div><!-- /.card-header -->
          <div class="card-body p-0 table-responsive">
            <table class="table table-hover table-striped">
              <thead>
                <tr>
                  <th><%= Store.human_attribute_name(:image) %></th>
                  <th><%= Store.human_attribute_name(:name) %></th>
                  <th><%= Store.human_attribute_name(:code) %></th>
                  <th><%= Store.human_attribute_name(:postal_code) %></th>
                  <th><%= Store.human_attribute_name(:prefecture_id) %></th>
                  <th><%= Store.human_attribute_name(:address_1) %></th>
                  <th><%= Store.human_attribute_name(:address_2) %></th>
                  <th><%= Store.human_attribute_name(:address_3) %></th>
                  <th><%= Store.human_attribute_name(:tel_no) %></th>
                  <th><%= Store.human_attribute_name(:blog_url) %></th>
                  <th><%= Store.human_attribute_name(:rss_url) %></th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @stores.each do |store| %>
                  <tr>
                    <td><%= thumbnail store.image %></td>
                    <td><%= store.name %></td>
                    <td><%= store.code %></td>
                    <td><%= store.postal_code %></td>
                    <td><%= store.prefecture&.name %></td>
                    <td><%= store.address_1 %></td>
                    <td><%= store.address_2 %></td>
                    <td><%= store.address_3 %></td>
                    <td><%= store.tel_no %></td>
                    <td><%= store.blog_url %></td>
                    <td><%= store.rss_url %></td>
                    <td><%= link_to(t('text.show'), [:admin, store]) if policy(store).show? %></td>
                    <td><%= link_to(t('text.edit'), edit_admin_store_path(store)) if policy(store).update? %></td>
                    <td><%= link_to(t('text.destroy'), [:admin, store], method: :delete, data: { confirm: t('text.are_you_sure') }) if policy(store).destroy? %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div><!-- /.card-body -->
          <div class="card-footer clearfix">
            <%= paginate @stores %>
          </div>
        </div><!-- /.card -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</section>

app/views/admin/stores/new.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.new') %> <%= Store.model_name.human %>
        </h1>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= render 'form', store: @store %>
          </div>
          <div class="card-footer clearfix">
            <%= link_to t('text.back'), admin_stores_path, class: 'card-link' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/stores/show.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.show') %> <%= Store.model_name.human %>
        </h1>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-12">
        <%= render 'shared/alert', alert: notice %>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <dl>
              <dt><%= Store.human_attribute_name(:image) %></dt>
              <dd><%= thumbnail @store.image %></dd>
            </dl>
            <dl>
              <dt><%= Store.human_attribute_name(:name) %></dt>
              <dd><%= @store.name %></dd>
            </dl>
            <dl>
              <dt><%= Store.human_attribute_name(:code) %></dt>
              <dd><%= @store.code %></dd>
            </dl>
            <dl>
              <dt><%= Store.human_attribute_name(:postal_code) %></dt>
              <dd><%= @store.postal_code %></dd>
            </dl>
            <dl>
              <dt><%= Store.human_attribute_name(:prefecture_id) %></dt>
              <dd><%= @store.prefecture&.name %></dd>
            </dl>
            <dl>
              <dt><%= Store.human_attribute_name(:address_1) %></dt>
              <dd><%= @store.address_1 %></dd>
            </dl>
            <dl>
              <dt><%= Store.human_attribute_name(:address_2) %></dt>
              <dd><%= @store.address_2 %></dd>
            </dl>
            <dl>
              <dt><%= Store.human_attribute_name(:address_3) %></dt>
              <dd><%= @store.address_3 %></dd>
            </dl>
            <dl>
              <dt><%= Store.human_attribute_name(:tel_no) %></dt>
              <dd><%= @store.tel_no %></dd>
            </dl>
            <dl>
              <dt><%= Store.human_attribute_name(:blog_url) %></dt>
              <dd><%= @store.blog_url %></dd>
            </dl>
            <dl>
              <dt><%= Store.human_attribute_name(:rss_url) %></dt>
              <dd><%= @store.rss_url %></dd>
            </dl>
          </div>
          <div class="card-footer clearfix">
            <%= link_to(t('text.edit'), edit_admin_store_path(@store), class: 'card-link') if policy(@store).update? %>
            <%= link_to(t('text.back'), admin_stores_path, class: 'card-link') if policy(Store).index? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>