config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # ----------
  # api
  # ----------
  mount_devise_token_auth_for 'User', at: 'api/v1/auth', controllers: {
    registrations: 'api/v1/auth/registrations'
  }
  namespace :api do
    namespace :v1 do
      resources :addresses
      resources :contacts,     only: %i[create]
      resources :coordinates,  only: %i[index show]
      resources :informations, only: %i[index show]
      resources :orders,       only: %i[index show]
      resources :pages,        only: %i[index show]
      resources :products,     only: %i[index show]
      resources :rankings,     only: %i[index show]
      resources :stores,       only: %i[index show]
      resources :store_blogs,  only: %i[index show]
      resources :variations,   only: %i[index show]
    end
  end

  # ----------
  # admin
  # ----------
  devise_for :admins, path: 'admin/auth', skip: %i[registrations], controllers: {
    sessions: 'admin/auth/sessions',
    unlocks:  'admin/auth/unlocks'
  }
  # only use update(disable sign up)
  as :admin do
    get 'admin/auth/edit' => 'admin/auth/registrations#edit', as: 'edit_admin_registration'
    put 'admin/auth' => 'admin/auth/registrations#update', as: 'admin_registration'
  end
  namespace :admin do
    root 'dashboards#show'
    resources :admins
    resources :brands
    resources :categories
    resources :colors
    resources :companies
    resources :contacts
    resources :coordinates
    resources :divisions
    resources :informations
    resources :pages
    resources :positions
    resources :products
    resources :orders
    resources :rankings
    resources :sizes
    resources :staffs
    resources :stores
    resources :store_blogs
    resources :tags
    resources :users
    resources :variations
  end
end

app/models/coordinate.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: coordinates
#
#  id         :bigint(8)        not null, primary key
#  staff_id   :bigint(8)
#  point_1    :text(65535)
#  point_2    :text(65535)
#  point_3    :text(65535)
#  comment    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Coordinate < ApplicationRecord
  belongs_to :staff, optional: true
  has_many :coordinates_products, dependent: :destroy
  has_many :products, through: :coordinates_products

  has_many_attached :images

  def image_paths
    images.map do |image|
      URI.join(
        Rails.application.config.action_controller.asset_host,
        Rails.application.routes.url_helpers.rails_blob_path(image, only_path: true)
      )
    end
  end
end

app/controllers/admin/coordinates_controller.rb
# frozen_string_literal: true

class Admin::CoordinatesController < Admin::ApplicationController
  before_action :set_coordinate, only: %i[show edit update destroy]

  # GET /coordinates
  def index
    @q = Coordinate.search(params[:q])
    authorize @coordinates = @q.result.page(params[:page])
  end

  # GET /coordinates/1
  def show; end

  # GET /coordinates/new
  def new
    authorize @coordinate = Coordinate.new
  end

  # GET /coordinates/1/edit
  def edit; end

  # POST /coordinates
  def create
    authorize @coordinate = Coordinate.new(coordinate_params)

    if @coordinate.save
      redirect_to [:admin, @coordinate], notice: t('notice.create.success', name: Coordinate.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /coordinates/1
  def update
    if @coordinate.update(coordinate_params)
      redirect_to [:admin, @coordinate], notice: t('notice.update.success', name: Coordinate.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /coordinates/1
  def destroy
    @coordinate.destroy
    redirect_to admin_coordinates_url, notice: t('notice.destroy.success', name: Coordinate.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_coordinate
    authorize @coordinate = Coordinate.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def coordinate_params
    params.require(:coordinate).permit(:staff_id, :point_1, :point_2, :point_3, :comment)
  end
end

app/controllers/api/v1/coordinates_controller.rb
# frozen_string_literal: true

class Api::V1::CoordinatesController < Api::V1::ApplicationController
  before_action :set_coordinate, only: %i[show]

  # GET /coordinates
  def index
    @coordinates = Coordinate.includes(:staff)
                             .with_attached_images
                             .search(params[:q]).result
                             .page(params[:page]).per(params[:per_page])

    paginate json: @coordinates
  end

  # GET /coordinates/1
  def show
    render json: @coordinate
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_coordinate
    @coordinate = Coordinate.find(params[:id])
  end
end

app/views/admin/coordinates/_form.html.erb
<%= form_with(model: [:admin, coordinate], local: true) do |form| %>
  <%= render 'shared/form_errors', errors: coordinate.errors %>

  <div class="form-group">
    <%= form.label :staff_id %>
    <%= form.collection_select :staff_id, Staff.all, :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :point_1 %>
    <%= form.text_area :point_1, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :point_2 %>
    <%= form.text_area :point_2, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :point_3 %>
    <%= form.text_area :point_3, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :comment %>
    <%= form.text_area :comment, class: 'form-control' %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/coordinates/edit.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.edit') %> <%= Coordinate.model_name.human %>
        </h1>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= render 'form', coordinate: @coordinate %>
          </div>
          <div class="card-footer clearfix">
            <%= link_to(t('text.show'), [:admin, @coordinate], class: 'card-link') if policy(@coordinate).show? %>
            <%= link_to(t('text.back'), admin_coordinates_path, class: 'card-link') if policy(Coordinate).index? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/coordinates/index.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= Coordinate.model_name.human %>
        </h1>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-12">
        <%= render 'shared/alert', alert: notice %>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <i class="fa fa-pencil"></i> <%= page_entries_info @coordinates %>
            <div class="card-tools d-flex">
              <%= link_to(t('text.new'), new_admin_coordinate_path, class: 'mr-3 mt-1') if policy(Coordinate).create? %>
              <%= paginate @coordinates %>
            </div>
          </div><!-- /.card-header -->
          <div class="card-body p-0 table-responsive">
            <table class="table table-hover table-striped">
              <thead>
                <tr>
                  <th><%= Coordinate.human_attribute_name(:staff_id) %></th>
                  <th><%= Coordinate.human_attribute_name(:point_1) %></th>
                  <th><%= Coordinate.human_attribute_name(:point_2) %></th>
                  <th><%= Coordinate.human_attribute_name(:point_3) %></th>
                  <th><%= Coordinate.human_attribute_name(:comment) %></th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @coordinates.each do |coordinate| %>
                  <tr>
                    <td><%= coordinate.staff&.name %></td>
                    <td><%= coordinate.point_1 %></td>
                    <td><%= coordinate.point_2 %></td>
                    <td><%= coordinate.point_3 %></td>
                    <td><%= coordinate.comment %></td>
                    <td><%= link_to(t('text.show'), [:admin, coordinate]) if policy(coordinate).show? %></td>
                    <td><%= link_to(t('text.edit'), edit_admin_coordinate_path(coordinate)) if policy(coordinate).update? %></td>
                    <td><%= link_to(t('text.destroy'), [:admin, coordinate], method: :delete, data: { confirm: t('text.are_you_sure') }) if policy(coordinate).destroy? %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div><!-- /.card-body -->
          <div class="card-footer clearfix">
            <%= paginate @coordinates %>
          </div>
        </div><!-- /.card -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</section>

app/views/admin/coordinates/new.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.new') %> <%= Coordinate.model_name.human %>
        </h1>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= render 'form', coordinate: @coordinate %>
          </div>
          <div class="card-footer clearfix">
            <%= link_to t('text.back'), admin_coordinates_path, class: 'card-link' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/coordinates/show.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-12">
        <h1 class="m-0 text-dark">
          <%= t('text.show') %> <%= Coordinate.model_name.human %>
        </h1>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-12">
        <%= render 'shared/alert', alert: notice %>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <dl>
              <dt><%= Coordinate.human_attribute_name(:staff_id) %></dt>
              <dd><%= @coordinate.staff&.name %></dd>
            </dl>
            <dl>
              <dt><%= Coordinate.human_attribute_name(:point_1) %></dt>
              <dd><%= @coordinate.point_1 %></dd>
            </dl>
            <dl>
              <dt><%= Coordinate.human_attribute_name(:point_2) %></dt>
              <dd><%= @coordinate.point_2 %></dd>
            </dl>
            <dl>
              <dt><%= Coordinate.human_attribute_name(:point_3) %></dt>
              <dd><%= @coordinate.point_3 %></dd>
            </dl>
            <dl>
              <dt><%= Coordinate.human_attribute_name(:comment) %></dt>
              <dd><%= @coordinate.comment %></dd>
            </dl>
          </div>
          <div class="card-footer clearfix">
            <%= link_to(t('text.edit'), edit_admin_coordinate_path(@coordinate), class: 'card-link') if policy(@coordinate).update? %>
            <%= link_to(t('text.back'), admin_coordinates_path, class: 'card-link') if policy(Coordinate).index? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>